### ISSUE TITLE
Is there any way to complete HTTP requests inside python script

### ISSUE THREAD

**Issue by ghost** [replit-archive/empythoned#19]
I'm running this example script on **Empythoned Demo**

``` python
import urllib
print urllib.urlopen("http://ipv4.icanhazip.com/").read()
```

I got an error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/urllib.py", line 26, in <module>
    import socket
  File "/lib/python2.7/socket.py", line 47, in <module>
    import _socket
ImportError: No module named _socket
```

So, I need to make a HTTP request inside python script. Is there any way?

**Comment by SamyBencherif** [comment]
Client side javascript cannot make HTTP requests to another domain

**Comment by EricSekyere** [comment]
looks like you are missing some dependencies or they are not copied over in the build script.
you will probably need to manually add it in your environment
